# Overlays for the Odroid platform

dtb-$(CONFIG_ARCH_ROCKCHIP) += \
	blueled_off.dtbo \
	dht11.dtbo \
	display_vu8s.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	i2c2.dtbo \
	mcp2515.dtbo \
	mcp2515_12mhz.dtbo \
	mcp2515_16mhz.dtbo \
	mcp2517fd.dtbo \
	onewire.dtbo \
	pwm3.dtbo \
	pwm7.dtbo \
	pwm8.dtbo \
	pwm9.dtbo \
	pwm10.dtbo \
	pwm11.dtbo \
	pwm12.dtbo \
	pwm13.dtbo \
	pwm15.dtbo \
	spi0.dtbo \
	spi1.dtbo \
	uart0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart1.dtbo \
	uart1-with-ctsrts.dtbo \
	uart2.dtbo \
	uart3.dtbo \
	uart4.dtbo \
	uart5.dtbo \
	weather_board_zero.dtbo \
