# Overlays for the Odroid platform

dtb-$(CONFIG_ARCH_MESON) += \
	dht11.dtbo \
	hktft32.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	mcp2515.dtbo \
	mcp2515_12mhz.dtbo \
	mcp2515_16mhz.dtbo \
	mcp2517fd.dtbo \
	onewire.dtbo \
	pwm_cd.dtbo \
	pwm_ef.dtbo \
	spi0.dtbo \
	uart0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart1.dtbo \
	weather_board_zero.dtbo \
