# Overlays for the Odroid platform

dtb-$(CONFIG_ARCH_ROCKCHIP) += \
	blueled_off.dtbo \
	dht11.dtbo \
	display_vu8m.dtbo \
	hktft32.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	i2c2.dtbo \
	mcp2515.dtbo \
	mcp2515_12mhz.dtbo \
	mcp2515_16mhz.dtbo \
	mcp2517fd.dtbo \
	onewire.dtbo \
	pcf8563.dtbo \
	pwm1.dtbo \
	pwm2.dtbo \
	pwm9.dtbo \
	pwm10.dtbo \
	pwm11.dtbo \
	spi0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart0.dtbo \
	uart1.dtbo \
	weather_board_zero.dtbo \
