# Overlays for the Odroid platform

dtbo-$(CONFIG_ARCH_ROCKCHIP_ODROIDM1) += \
	display-vu8m.dtbo \
	hktft32.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	pwm1-0.dtbo \
	pwm1-1.dtbo \
	pwm2-0.dtbo \
	pwm2-1.dtbo \
	pwm9.dtbo \
	spi0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart0.dtbo \
	uart1.dtbo \
	ov5647.dtbo \
	imx219.dtbo \
	imx477.dtbo \
	rknpu.dtbo

targets += $(dtbo-y)
always := $(dtbo-y)
