# Overlays for the Odroid platform

dtb-$(CONFIG_ARCH_ROCKCHIP) += \
	blueled_off.dtbo \
	board_multiio.dtbo \
	board_multiio_canfd.dtbo \
	board_multiio_oled.dtbo \
	board_stepper.dtbo \
	dht11.dtbo \
	hktft32.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	i2c4.dtbo \
	i2c5.dtbo \
	mcp2515.dtbo \
	mcp2515_12mhz.dtbo \
	mcp2515_16mhz.dtbo \
	mcp2517fd.dtbo \
	onewire.dtbo \
	pcf8563.dtbo \
	pwm1.dtbo \
	pwm2.dtbo \
	pwm3.dtbo \
	pwm11.dtbo \
	pwm14.dtbo \
	spi0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart0.dtbo \
	uart1.dtbo \
	uart5.dtbo \
	uart7.dtbo \
	uart9.dtbo \
	weather_board_zero.dtbo \
