dtbo-y += \
	display_vu5s.dtbo \
	display_vu8s.dtbo \
	display_waveshare_1inch47.dtbo \
	display_waveshare_1inch69.dtbo \
	i2c0.dtbo \
	i2c1.dtbo \
	pwm1.dtbo \
	pwm2.dtbo \
	pwm3.dtbo \
	spdif_sound.dtbo \
	spi0.dtbo \
	uart0.dtbo \
	uart0-with-ctsrts.dtbo \
	uart1.dtbo \
	weather_board_zero.dtbo

targets += $(dtbo-y)
always-y := $(dtbo-y)
